### ISSUE TITLE
Unable to resolve dependency 'FubarCoder.RestSharp.Portable.Core'			

### ISSUE THREAD

**Issue by GokulprasathG-P** [sendinblue/APIv3-csharp-library#36]
When i try to install nuget pkg in visual studio 2019 in a asp.net project, its showing me a error of unable to resolve dependency 'FubarCoder.RestSharp.Portable.Core', please help me with this

**Comment by amitsendinblue** [comment]
Hi @GokulprasathG-P, could you please elaborate more on this like the version of .net framework you are using and the exact issue which you are facing with some screenshot or video or sample code to replicate the same. So that we can investigate better.
FYI we support:
.NET Core >=1.0
.NET Framework >=4.6.1

**Comment by amitsendinblue** [comment]
Closing this as there is no response for more than 11 days.
