### ISSUE TITLE
Introduction of sib_api_v3_sdk.Model.Task introduces ambiguity

### ISSUE THREAD

**Issue by Tilwin90** [sendinblue/APIv3-csharp-library#53]
With the upgrade to package version `3.3.0` on our solution I noticed the introduction of "Task" type that adds ambiguity with respect to "System.Threading.Tasks.Task" in files operating on `sib_api_v3_sdk.Model`.  

While not a hard to fix issue, as one can resolve the ambiguity with a using statement pointing to the System.Threading task, it does introduce a breaking change that could be avoided and instead requires change from anyone using your package.

To add further, this bleeds into the rest of the solution wherever IDEs (like Rider, or Visual Studio) would be requested to  resolve import for the type "Task", as now your type shows up as an option and can be quite disruptive to the day by day work on the project (previously I didn't have to wonder "am I picking the right Task type" whenever I added an async method in my codebase).  

I strongly recommend renaming this type so it doesn't clash with a fundamental .NET type and it's a change done recently in your packages.  

Thank you!

**Comment by amitsendinblue** [comment]
Hello @Tilwin90, The name "Task" we can not replace as it represents some functional business flow at our end. This needs to be taken care code level.

**Comment by MSIH** [comment]
I am a beginner programmer. what is the solution. my .net core 7 code will not build 

```csharp
public class EmailSender
    {
        private readonly ILogger _logger;

        public EmailSender(
                           ILogger<EmailSender> logger)
        {            
            _logger = logger;
        }

       
        public async Task SendEmailAsync(string toEmail, string subject, string message)
        {
            await Execute(subject, message, toEmail);
        }
```

**Comment by MSIH** [comment]
ok. intellasense suggested this and it worked
```csharp
using Task = System.Threading.Tasks.Task;
```

**Comment by avisvard** [comment]
@amitsendinblue I must say that I do not agree with you regarding that this should be taken care of at the code level of each project as Task is a defacto reserved name. While not being part of the list of reserved keywords (see https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ ) it is part of the System.Runtime assembly (see https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task?view=net-8.0 )
I understand that this library is generated from the OpenAPI specifications (without manual handling?). I'd recommend to add some manual handling in order to provide a better SDK to improve the developer experience (by reducing brain load using your library). As a suggestion I'd recommend using something such as SiBTask, SendInBlueTask or based on the end user UI call it Interaction.
